### ISSUE TITLE
Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by ygguser** [YGGverse/YGGo#9]
We will get an error message if we try to enter such a search query: `http://[202:5855:991b:6e6b:e306:53f2:b058:2186]` or even just `/`.

**Comment by d47081** [comment]
Thanks for report!

it maybe depends of the [last update](https://github.com/YGGverse/YGGo/commit/9ae91ee187a89846c4c089e862c1eaaa44fb700d) - where I have enabled [extended search syntax](https://sphinxsearch.com/docs/current.html#extended-syntax)

on this example:

```
quorum matching operator:

"the world is a wonderful place"/3
```

so fixed, but not closing the issue, 

maybe I need to improve it because 
extended syntax constructions with following chars was disabled 
https://github.com/YGGverse/YGGo/blob/main/library/filter.php#L60

**Comment by d47081** [comment]
Well, 

finally have implemented 'not-safe' special chars filtering for regular users:

https://github.com/YGGverse/YGGo#default-constructions

for geeks, has been implemented special mode 
where they can play with index by using their own SphinxQL requests:

https://github.com/YGGverse/YGGo#extended-syntax

Let's maybe close the subject, please reopen if I something missed in the `default` mode.

p.s. not disabling errors print on a screen to make people able to report or contribute.
